version: "3.8"

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/app_db
    depends_on:
      - mongo
    command: node dist/main
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo:4.4
    container_name: mongo_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=app_db
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
